apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebba-cnn
  namespace: labinf
  labels:
    app: ebba_cnn
spec:
  replicas: 1
  selector:
    matchLabels:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ebba-cnn
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: acceleration
                operator: In
                values:
                - gpu
      containers:
      - name: ebba-cnn
        image: ebbab/ebba_cnn_docker
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          limits:
            cpu: "10"
            memory: 96000Mi
            nvidia.com/gpu: "1"
          requests:
            cpu: "1"
            memory: 64000Mi
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/jovyan
          name: notebook-home
          subPath: ebba-home
        - mountPath: /scratch-shared
          name: scratch-shared
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /home/jovyan
        image: busybox
        imagePullPolicy: Always
        name: volume-mount-set-permissions-on-nfs-volume-home-mount
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/jovyan
          name: notebook-home
          subPath: ebba-home
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: notebook-home
        persistentVolumeClaim:
          claimName: notebook-homes-pvc
      - hostPath:
          path: /media/scratch/shared
          type: DirectoryOrCreate
        name: scratch-shared